name: dart_dependency_analyzer
description: A sample command-line application with basic argument parsing.
version: 0.0.1
homepage: https://github.com/jersonal-com/dart_dependency_analyzer
repository: https://github.com/jersonal-com/dart_dependency_analyzer

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.5.0
  http: ^1.4.0
  pub_semver: ^2.2.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
